<a href="https://colab.research.google.com/github/CeHaga/dsa-python-chapter-8/blob/main/Exercicios_PythonDSA_Cap08.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Exercises from Chapter 8 from Data Science Academy's course Python Fundamentals for Data Analysis

https://github.com/dsacademybr/PythonFundamentos/blob/master/Cap08/Notebooks/DSA-Python-Cap08-Exercicios.ipynb

In [2]:
import pandas as pd
import numpy as np

##Exercício 1

In [3]:
# Crie um array NumPy com 1000000 e uma lista com 1000000.
# Multiplique cada elemento do array e da lista por 2 e calcule o tempo de execução com cada um dos objetos (use %time).
# Qual objeto oferece melhor performance, array NumPy ou lista?

arrayNumpy = np.ones(1000000)
arrayPython = [1] * 1000000

In [4]:
%time
map(lambda x: x*2, arrayPython)

CPU times: user 2 µs, sys: 1e+03 ns, total: 3 µs
Wall time: 4.53 µs


In [5]:
%time
map(lambda x: x*2, arrayNumpy)

CPU times: user 3 µs, sys: 1e+03 ns, total: 4 µs
Wall time: 7.87 µs


##Exercício 2

In [6]:
lista = np.ones(10)
lista[5:9] = [0] * 4
lista

array([1., 1., 1., 1., 1., 0., 0., 0., 0., 1.])

##Exercício 3

In [11]:
matriz = np.ones((1,1,1))
matriz[0]

array([[1.]])

## Exercício 4

In [70]:
matriz = np.random.rand(3,4)
print('Matriz completa')
print(matriz)
print('\nTerceira linha')
print(matriz[2])
print('\nPrimeira e segunda linha')
print(matriz[0])
print(matriz[1])
print('\nSegunda e terceira coluna')
print(matriz[:,1])
print(matriz[:,2])

Matriz completa
[[0.67271377 0.3255716  0.01849678 0.0844768 ]
 [0.2820107  0.2609695  0.71615347 0.05397227]
 [0.05499737 0.3873129  0.49033801 0.20258717]]

Terceira linha
[0.05499737 0.3873129  0.49033801 0.20258717]

Primeira e segunda linha
[0.67271377 0.3255716  0.01849678 0.0844768 ]
[0.2820107  0.2609695  0.71615347 0.05397227]

Segunda e terceira coluna
[0.3255716 0.2609695 0.3873129]
[0.01849678 0.71615347 0.49033801]


## Exercício 5

In [13]:
arr = np.arange(15).reshape((3, 5))
arr.transpose()

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

## Exercício 6

In [21]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])
arrFinal = xarr
arrFinal[~cond] = yarr[~cond]
arrFinal

array([1.1, 2.2, 1.3, 1.4, 2.5])

## Exercício 7

In [26]:
with open('array.npy','wb') as f:
  A = np.ones(10)
  np.save(f,A)
with open('array.npy','rb') as f:
  B = np.load(f)
  print(B)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


## Exercício 8

In [27]:
import pandas as pd
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c', 'a', 'b'])
obj.unique()

array(['c', 'a', 'd', 'b'], dtype=object)

## Exercício 9

In [59]:
import requests
import json
url = 'https://api.github.com/repos/pandas-dev/pandas/issues'
resp = requests.get(url)

data = json.loads(resp.content)
df = pd.json_normalize(data)
df[['number','title','labels','state']]

number  ... state
0    40149  ...  open
1    40148  ...  open
2    40147  ...  open
3    40146  ...  open
4    40145  ...  open
5    40144  ...  open
6    40143  ...  open
7    40142  ...  open
8    40141  ...  open
9    40140  ...  open
10   40139  ...  open
11   40137  ...  open
12   40135  ...  open
13   40134  ...  open
14   40131  ...  open
15   40130  ...  open
16   40129  ...  open
17   40127  ...  open
18   40124  ...  open
19   40123  ...  open
20   40122  ...  open
21   40121  ...  open
22   40115  ...  open
23   40114  ...  open
24   40113  ...  open
25   40112  ...  open
26   40111  ...  open
27   40110  ...  open
28   40103  ...  open
29   40101  ...  open

[30 rows x 4 columns]

## Exercício 10

In [83]:
import os
os.remove('banco.bd') if os.path.exists('banco.bd') else None

import sqlite3
con = sqlite3.connect('banco.bd')
cur = con.cursor()

sql_create = 'create table pessoa('\
'id integer primary key autoincrement,'\
'nome varchar(50),'\
'idade integer);'
cur.execute(sql_create)

sql_insert = 'insert into pessoa(nome,idade) values (?,?)'
pessoas = [('ABC',20),('DEF',50)]
for pessoa in pessoas:
  cur.execute(sql_insert,pessoa)

df = pd.read_sql_query('select * from pessoa',con)
df

id nome  idade
0   1  ABC     20
1   2  DEF     50